In [67]:
import sklearn
print(sklearn.__version__)

1.6.1

## FIT AND PREDICT ESTIMATORS

.fit()

.predict()

In [68]:
from sklearn import set_config
set_config(display="Diagram")

In [69]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(random_state=42)

X = [[1,2,3],[11,22,33]] # 2samples each of 3 features
y = [0,1] # Classes of each sample
model.fit(X,y) # This is training part

RandomForestClassifier(random_state=42)

In [70]:
# predict
model.predict(X)

array([0, 1])

In [71]:
X = [[22,33,44],[11,12,13]]
model.predict(X)

array([1, 0])

In [72]:
X = [[22,33,44],[11,12,13]]
model.predict_proba(X)
    # Prints the probability of each sample to be in the class trained on

array([[0.26, 0.74],
       [0.6 , 0.4 ]])

# TESTING FOR THE LOGISTIC REGRESSION

In [73]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
X ,y = load_iris(return_X_y=True)
print(X[:2,:])
print(y[:2])
clf = LogisticRegression(random_state=0, max_iter=1000).fit(X,y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]]
[0 0]

In [74]:
clf.predict(X[:2,:])

array([0, 0])

In [75]:
clf.predict_proba(X[:2,:])

array([[9.81557202e-01, 1.84427831e-02, 1.44809203e-08],
       [9.71331260e-01, 2.86687094e-02, 3.01371913e-08]])

In [76]:
#ACCURACY
clf.score(X,y)

0.9733333333333334

# TRANSFORMERS AND PREPROCESSORS

.fit()


.transform()      

{It's like prediction}


Use case on train_test_split

In [77]:
from sklearn.preprocessing import StandardScaler
import numpy as np

X = np.array([1 ,2 ,3, 4 ,5, 6]).reshape(-1,1)

ScaledX = StandardScaler().fit(X) # Uses this data to calculate mu and sigma
ScaledX.transform(X) # Uses it to transform the parameter dataset

array([[-1.46385011],
       [-0.87831007],
       [-0.29277002],
       [ 0.29277002],
       [ 0.87831007],
       [ 1.46385011]])

In [78]:
#Chaining is also possible
StandardScaler().fit(X).transform(X)
# or
StandardScaler().fit_transform(X)

array([[-1.46385011],
       [-0.87831007],
       [-0.29277002],
       [ 0.29277002],
       [ 0.87831007],
       [ 1.46385011]])

# Sometimes you may want to perform different transformation in different columns


   ___### ColumnTransformer

In [79]:
import pandas as pd

# Create sample data
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [25, 30, 22, 28, 35],
    "City": ["Kathmandu", "Pokhara", "Biratnagar", "Lalitpur", "Bhaktapur"],
    "Score": [88.5, 92.0, 76.5, 85.0, 90.3],
    "Passed": [True, True, False, True, True]
}

# Create DataFrame
df = pd.DataFrame(data)

# Display it
df

      Name  Age        City  Score  Passed
0    Alice   25   Kathmandu   88.5    True
1      Bob   30     Pokhara   92.0    True
2  Charlie   22  Biratnagar   76.5   False
3    David   28    Lalitpur   85.0    True
4      Eva   35   Bhaktapur   90.3    True

In [80]:
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import OneHotEncoder
column_trans = ColumnTransformer(
    [
        ('City_Category', OneHotEncoder(dtype='int'),['City']),
        ('Name_Vectors', CountVectorizer(), 'Name')
    ],
    remainder='passthrough'
)

In [81]:
column_trans.fit(df)

ColumnTransformer(remainder='passthrough',
                  transformers=[('City_Category', OneHotEncoder(dtype='int'),
                                 ['City']),
                                ('Name_Vectors', CountVectorizer(), 'Name')])

In [82]:
column_trans.get_feature_names_out()

array(['City_Category__City_Bhaktapur', 'City_Category__City_Biratnagar',
       'City_Category__City_Kathmandu', 'City_Category__City_Lalitpur',
       'City_Category__City_Pokhara', 'Name_Vectors__alice',
       'Name_Vectors__bob', 'Name_Vectors__charlie',
       'Name_Vectors__david', 'Name_Vectors__eva', 'remainder__Age',
       'remainder__Score', 'remainder__Passed'], dtype=object)

In [83]:
column_trans.transform(df)

array([[0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 25, 88.5, True],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 30, 92.0, True],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 22, 76.5, False],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 28, 85.0, True],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 35, 90.3, True]], dtype=object)

In [84]:
df

      Name  Age        City  Score  Passed
0    Alice   25   Kathmandu   88.5    True
1      Bob   30     Pokhara   92.0    True
2  Charlie   22  Biratnagar   76.5   False
3    David   28    Lalitpur   85.0    True
4      Eva   35   Bhaktapur   90.3    True

## TRANSFOMERS AND ESTIMATORS can be combined together into a single unifying object called Pipeline

In [85]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [86]:
# CREATION OF PIPELINE OBJECT
pipe = make_pipeline(
    StandardScaler(), # All the rest should be transformer
    LogisticRegression() # Last one can be estimator/transformer
)

In [87]:
X, y = load_iris(return_X_y = True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [88]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

In [89]:
# WE CAN USE IT LIKE ANY OTHER ESTIMATOR
accuracy_score(pipe.predict(X_test), y_test)

1.0

# MODEL EVALUATION

In [90]:
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate

X, y = make_regression(n_samples=100, random_state=0)
lr = LinearRegression()

In [97]:
result = cross_validate(lr, X, y)
# Defaults to 5-fold validation with R^2 metric
  # 4 subsets for training and 1 for validation

In [98]:
X.shape

(100, 100)

In [99]:
y.shape

(100,)

In [103]:
# result['score_time']
result['test_score']

array([0.78066591, 0.62015804, 0.88685321, 0.69604852, 0.50904085])

# AUTOMATED PARAMETER SEARCH
## i.e. Hyperparameter Tuning

In [105]:
from sklearn.datasets import fetch_california_housing
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from scipy.stats import randint

In [107]:
X, y = fetch_california_housing(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

#Define the parameter space that will be seaerched over
# defining the parameter boundary for the hyperparameter space
param_distributions = {
    'n_estimators':randint(1,5),
    'max_depth':randint(5,10)
}

#Create a search object
search = RandomizedSearchCV(
    estimator=RandomForestRegressor(random_state=0),
    n_iter=5,
    param_distributions=param_distributions,
    random_state=0
)


#Perform the search
search.fit(X_train, y_train)

RandomizedSearchCV(estimator=RandomForestRegressor(random_state=0), n_iter=5,
                   param_distributions={'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7fbbc1ec0e90>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x7fbbcadff650>},
                   random_state=0)

In [108]:
# e.g
# Iteration	n_estimators	max_depth	Meaning
# 1	        3	            7	          Build 3 trees, each with depth ≤ 7
# 2	        2	            9	          Build 2 trees, each with depth ≤ 9
# 3	        4	            6	          Build 4 trees, each with depth ≤ 6
# 4	        1	            5	          Build 1 tree, with depth ≤ 5
# 5	        2	            8	          Build 2 trees, each with depth ≤ 8

In [109]:
search.best_params_

{'max_depth': 9, 'n_estimators': 4}

In [110]:
search.score(X_test,y_test)
#It's corresponding to the best params

0.735363411343253