# LEARNING THE REGEX

In [42]:
import pandas as pd

In [43]:
dfNew = pd.read_csv("/content/drive/MyDrive/WebScrapedCSVs/movies.csv")

# *Handling NaN*

In [44]:
dfNew.iloc[6477]

adult                     False
genre_ids              [18, 36]
original_language            tr
overview                    NaN
popularity                0.266
release_date         2015-07-10
title                       Ret
vote_average              6.392
vote_count                  325
Name: 6477, dtype: object

In [45]:
dfNew['overview'] = dfNew['overview'].fillna('')

In [46]:
dfNew.iloc[6477]

adult                     False
genre_ids              [18, 36]
original_language            tr
overview
popularity                0.266
release_date         2015-07-10
title                       Ret
vote_average              6.392
vote_count                  325
Name: 6477, dtype: object

In [47]:
import re

In [48]:
text = '''
          $4.3 billion is the net worth to be achieved
          but the
          thing is that FY 1032 WAS $23.555 billion is the most this guy can take
          but the amount fy2022 IS THE KING OF of $123 billion
       '''

# SOME BASICS
    # [ABC] it means any element inside the bracket is selected
    # [ABC]+ it means any combination of them is to be shift_selection_mode
    # [ABC]* same as above but will select the empty space as well
    # () it means after applying the regex select the content inside it and return
    # \d it means numbers
    # \d{10} it means numbers repeated 10 times {} represents repetitions
    # [^abc] it means except the a,b,c elements
    # [1-9] it means numbers 1 to 9
    # (?i)apple it means case insensitive extraction of word apple
    # [\s]* any combination of space i.e white space or nothing
       # \s it means white space
       # \S it means anything except white space

    # . it means anything except the newline
    # ? it means lazy select as much as possible without being greedy
      # use case:  <.*?> anything that is tag
pattern = '(?i)fy[\s]*[\d]{4}[^\$]+\$[\d\.]+ bILLion'
tagPattern = '<.*>'

  #[^\$]+ means after that fyDATE any text except $ upto $ in any combination is to
  #be extracted

<>:25: SyntaxWarning: invalid escape sequence '\s'
<>:25: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-999739083.py:25: SyntaxWarning: invalid escape sequence '\s'
  pattern = '(?i)fy[\s]*[\d]{4}[^\$]+\$[\d\.]+ bILLion'

# BASIC FUNCTIONS

# re.finall()

# re.search()

# ans.group()

In [49]:
# this findall funciton of re can has flags like IGNORECASE to disregard the CASE SENSITIVITY
amount_mentioned = re.findall(pattern, text, flags=re.IGNORECASE) # Here flags one works for the billion
first_selection = re.search(pattern, text, flags=re.IGNORECASE)
print(amount_mentioned)
print(first_selection.group()) # search help to see only first selection

['FY 1032 WAS $23.555 billion', 'fy2022 IS THE KING OF of $123 billion']
FY 1032 WAS $23.555 billion

# re.compile

In [50]:
# using the re.compile to compile regex into an object
pattern2 ='(?i)fy[\s]*[\d]{4}[^\$]+\$[\d\.]+ bILLion'
patternObj = re.compile(pattern2)
amount_mentioned2 = patternObj.findall(text)
first_selection2 = patternObj.search(text)
print(amount_mentioned2)
print(first_selection2.group())

['FY 1032 WAS $23.555 billion', 'fy2022 IS THE KING OF of $123 billion']
FY 1032 WAS $23.555 billion

<>:2: SyntaxWarning: invalid escape sequence '\s'
<>:2: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-1068716943.py:2: SyntaxWarning: invalid escape sequence '\s'
  pattern2 ='(?i)fy[\s]*[\d]{4}[^\$]+\$[\d\.]+ bILLion'

# *HTML CONTENT FILTERING and LOWERCASING*

In [51]:
## This was to test where the issue was while applying the remove_tags
# i=0

In [52]:
def remove_tags(text):
  ## This was to test where the issue was while applying the remove_tags
  # global i
  # i+=1
  # print(f"{type(text)}+{i}")
  tagPattern = '<.*?>'
  patternObj = re.compile(tagPattern)
  return patternObj.sub('',text)

In [53]:
text = '''
          <!DOCTYPE html>
          <html>
            <body>
              <p>Hello, world!</p>
            </body>
          </html>
       '''

In [54]:
filtered_html = remove_tags(text)
print(filtered_html)
print(filtered_html.strip())

              Hello, world!



Hello, world!

In [55]:
import pandas as pd

In [64]:
# df = pd.DataFrame({
#     "review": [
#         "<p>Great product, loved it!</p>",
#         "<div>Not satisfied with the quality.</div>",
#         "<span>Amazing service and fast delivery!</span>"
#     ]
# })
df = pd.DataFrame({})
df['review'] = dfNew['overview'].iloc[:100]

In [65]:
len(df['review'])

100

In [66]:
df['filtered_review'] = df['review'].apply(remove_tags)

In [67]:
# NOTE
  #  df['review'] column of a dataframe is a pandas series object
df['lower_case_filtered_review'] = df['filtered_review'].apply(lambda x: x.lower())
   # the lambda x helps to pick up every element of the pandas series and store it in x then we have
   # applied the x.lower() on it

In [68]:
df

,review,filtered_review,lower_case_filtered_review
0,Imprisoned in the 1940s for the double murder ...,Imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...
1,"Spanning the years 1945 to 1955, a chronicle o...","Spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o..."
2,In the continuing saga of the Corleone crime f...,In the continuing saga of the Corleone crime f...,in the continuing saga of the corleone crime f...
3,The true story of how businessman Oskar Schind...,The true story of how businessman Oskar Schind...,the true story of how businessman oskar schind...
4,The defense and the prosecution have rested an...,The defense and the prosecution have rested an...,the defense and the prosecution have rested an...
...,...,...,...
95,"Set in the 22nd century, The Matrix tells the ...","Set in the 22nd century, The Matrix tells the ...","set in the 22nd century, the matrix tells the ..."
96,The invasion of a village in Byelorussia by Ge...,The invasion of a village in Byelorussia by Ge...,the invasion of a village in byelorussia by ge...
97,"Roberto, a shy law student in Rome, meets Brun...","Roberto, a shy law student in Rome, meets Brun...","roberto, a shy law student in rome, meets brun..."
98,"Tony Lip, a bouncer in 1962, is hired to drive...","Tony Lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive..."
99,A peculiar neighbor offers hope to a recent wi...,A peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...

In [69]:
# Note:
  # a? it means one a or empty
text = "a aa aaa aaaa"
pattern = 'a?'
import re
patternObj = re.compile(pattern)
output = patternObj.findall(text)
print(output)

['a', '', 'a', 'a', '', 'a', 'a', 'a', '', 'a', 'a', 'a', 'a', '']

# *PUNCTUATION REMOVAL*

1.   List item
2.   List item

In [70]:
import string, time
punc = string.punctuation
print(punc)
text3 = '''
So—let me begin (if “beginning” is even the right word, since everything feels like it has already begun, paused, resumed, collapsed, restarted…)—by saying this: the world, in all its noise and silence, is a paragraph itself, a sentence strung together with commas, dashes, question marks, and ellipses… don’t you think? Each day starts abruptly—alarm clocks blaring, phones vibrating, notifications exploding (!)—and yet ends quietly: sighs, yawns, a whisper of goodnight. In between those bookends (yes, I see life as a shelf of words, messy, unedited, half-erased), we cram in meetings, conversations, mistakes, promises, regrets—each separated by commas, joined by semicolons, occasionally punctuated by question marks (why me? why now? why this?), and sometimes interrupted—rudely, violently, chaotically—by dashes that split thought from thought. It’s almost unbearable: the constant motion, the relentless noise, the flickering screens, the pressure to answer (texts, emails, calls, questions, demands, deadlines, expectations…). Yet even in the chaos (or perhaps because of it), punctuation saves us: the pause of a comma lets us breathe; the full stop ends the madness (at least for a sentence); the dash introduces surprise—like a door slammed open mid-thought; the ellipsis lingers, reminding us that nothing is ever complete… not yet. And, of course, the exclamation point—ah, the exclamation!—shouts into the void: excitement, fear, frustration, joy, all at once.

Consider yesterday: I walked (hurried, stumbled, half-ran) through rain-soaked streets, my umbrella breaking, my shoes squeaking, my phone buzzing (again and again—relentless!), while overhead thunder rolled—boom! crash!—as if the sky itself were arguing. People passed (faces blurred, expressions unreadable, voices drowned by engines, horns, and sirens), and I thought—strangely, suddenly—“Is this life, or just punctuation strung into chaos?” Because everywhere I looked, punctuation lived: stop signs (periods!), traffic lights blinking red-yellow-green (commas, colons, semicolons), billboards shouting SALE! NOW! LIMITED TIME! (exclamations littered like confetti), and conversations snatched mid-air: “Wait—did you see…?” “No, but—” “Really?!” “Unbelievable…” And in that flood of marks, I realized: perhaps language isn’t just what we speak, but what surrounds us, presses against us, frames us.

Even at home, punctuation invades: the messy kitchen counter with coffee cups (parentheses around sleepless nights), the calendar with circled dates (exams, interviews, appointments—oh no!), the sticky notes plastered everywhere (imperatives ending with exclamation marks: “Buy milk!” “Call mom!” “Finish report!”). The computer screen—don’t get me started—overflows with tabs (commas and commas and commas), error messages (periods in disguise), passwords and codes (colons and dashes), while beneath it all the hum of electricity adds an ellipsis of sound. And when silence finally comes (rare, precious, fragile), it too is punctuation: the ellipsis of breath, the dash of heartbeat, the full stop of sleep.

But let’s not pretend punctuation is only external—it’s inside us too: the pulse (tick, tick, tick—comma, comma, comma), the sigh (ellipsis…), the sudden gasp (exclamation!), the whispered “maybe?” (question mark). Even thought itself is punctuated: start—pause—restart; think, hesitate, revise; argue (internally), concede (reluctantly), wonder (endlessly…). Doesn’t your mind, late at night, look like a cluttered sentence—fragments stitched with commas, broken by dashes, unresolved with ellipses? Mine certainly does.

And so, I ask—quietly, cautiously, almost rhetorically—what are we, if not punctuation embodied? People who dash from place to place; people who pause, hesitate, comma after comma; people who scream exclamations into empty rooms; people who end things with a cruel, sharp, irreversible period; people who let things trail, unresolved, with an ellipsis… And isn’t it beautiful, strange, terrifying? That meaning itself depends on the tiny hooks and dots and curves we scatter across paper (or screen)? Without them, we drown; with them, we survive. So yes—though the world keeps spinning (too loud, too fast, too much!), though our voices fracture (shouting, whispering, breaking), though our stories overlap and collide (clash! crash! splinter!)—we continue, stubbornly, rhythmically, desperately—comma by comma, dash by dash, ellipsis after ellipsis—until the final punctuation (which none of us can escape): the period, the end.
'''
text2 = "“Listen,” she began—hesitant, uncertain, but determined—“we’ve got to talk about… everything: the noise, the silence, the confusion, the chaos! Can’t you see it? The walls are closing in; the lights are flickering (on, off, on, off… endlessly); the clock—tick, tick, tick—keeps reminding us that time isn’t patient, not for you, not for me, not for anyone. Do you remember yesterday? Or was it last week? No—last month! When we sat in that crowded café (you know the one: small tables, squeaky chairs, coffee stains on every surface), and you said—casually, almost carelessly—‘We’ll figure it out’? Ha! Figure it out? Really? With deadlines looming, with bills piling up, with voices (internal and external!) shouting: ‘Hurry up! Move faster! Don’t stop!’ How can anyone figure it out in such a storm? And yet, here we are: still breathing, still moving, still… hoping (aren’t we?). Strange, isn’t it—how commas, dashes, ellipses (…) and exclamation marks (!) become our only tools to capture the rhythm of panic, the heartbeat of fear, the fragile whisper of hope? Look around—at the books (half-read, dog-eared, underlined!), at the papers (scribbled notes, arrows, question marks??), at the empty cups (coffee, tea, whatever), at the windows streaked with rain (or is it condensation?), at the calendar—pages torn, scribbled, circled dates—mocking us with their persistence. And yet—despite it all—don’t you feel a pull, a spark, a kind of… stubborn resilience? That voice—quiet, soft, almost lost—saying: “Wait, breathe, hold on.” Maybe it’s naïve; maybe it’s foolish; maybe it’s exactly what we need. After all, punctuation isn’t just grammar—it’s survival: the pause (comma), the break (dash), the finality (period), the continuation (semicolon), the uncertainty (question mark?), the plea (exclamation!). Without them, without these marks, without this rhythm—how would we tell our stories, how would we confess our fears, how would we shout our joy? So yes—though the world spins (too fast, too loud, too much!), though the hours vanish (slipping, sliding, evaporating…), though our thoughts collide (crash! bang! splinter!)—we write, we speak, we stumble forward… one sentence, one fragment, one punctuation mark at a time."
text = "Wow! Can you believe it?—yesterday, at exactly 3:45 p.m., I walked into the café (yes, the one on Main Street), ordered a “double-shot espresso, extra hot,” and, to my surprise, the barista shouted: “Finally, someone who knows what they want!” I laughed—perhaps too loudly—because, honestly, who expects a compliment at that hour? Anyway, after paying $4.75 (plus tax!), I sat down, opened my notebook, and began scribbling—words, doodles, arrows, even question marks (???)—as though my pen had a mind of its own. Strange, isn’t it?"

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [71]:
def remove_punc(text):
  # puncObj = re.compile(punc)
  # return(puncObj.sub(r'',text)) ## Cause each character is itself a reserved symbol
  for char in punc:
    text = text.replace(char, '')
  return(text)

In [72]:
startTime = time.time()
remove_punc(text3)
endTime = time.time()
normTime = endTime-startTime
print("time taken = "+str(normTime)+"s")

time taken = 0.0001735687255859375s

In [73]:
# Standard way of punctuation removal
def stdPuncRemoval(text):
  # maketrans(chartoreplace, chartoreplaceWith, chartoEliminate) it makes table for it
  # using that table translate function performs actions on the text
  return (text.translate(str.maketrans('','',punc)))

In [74]:
startTime = time.time()
stdPuncRemoval(text3)
endTime = time.time()
stdTime = endTime-startTime
print("time taken = "+str(stdTime)+"s")

time taken = 0.0006771087646484375s

In [75]:
ratio = normTime/stdTime
print(ratio)
### HAHA i thought this was supposed to be the faster method.

0.2563380281690141

# *CHATWORD REPLACEMENT*

In [76]:
chat_words = {
    "LOL": "Laughing Out Loud",
    "BRB": "Be Right Back",
    "BTW": "By The Way",
    "IDK": "I Don’t Know",
    "IMO": "In My Opinion",
    "IMHO": "In My Humble Opinion",
    "TTYL": "Talk To You Later",
    "OMG": "Oh My God",
    "FYI": "For Your Information",
    "ASAP": "As Soon As Possible",
    "BFF": "Best Friends Forever",
    "DM": "Direct Message",
    "JK": "Just Kidding",
    "NP": "No Problem",
    "ROFL": "Rolling On the Floor Laughing",
    "SMH": "Shaking My Head",
    "TBF": "To Be Fair",
    "ICYMI": "In Case You Missed It",
    "AFK": "Away From Keyboard",
    "YOLO": "You Only Live Once"
}
# sentences = [
#     "<p>LOL, that meme was too funny 😂</p>",
#     "BRB... I need to grab some water.",
#     "<b>BTW</b>, did you check your email today?",
#     "IDK 🤔 what to eat for dinner tonight...",
#     "IMO, Python is the <i>best</i> programming language!",
#     "IMHO—that movie was overrated; not worth it.",
#     "TTYL :) I have a meeting now.",
#     "<h1>OMG!</h1> I can’t believe you won the contest!!!",
#     "FYI: the deadline has been extended <br/>",
#     "Please reply ASAP—it's urgent.",
#     "She’s my BFF ❤️ we’ve known each other since school.",
#     "Send me the details in a DM (Direct Message).",
#     "JK 😅 I wasn’t being serious...",
#     "NP 👍 I’ll handle it for you.",
#     "<div>That joke had me ROFL 😂😂😂</div>",
#     "SMH... people still fall for scams online?!",
#     "TBF, he did warn you before—remember?",
#     "ICYMI, here’s the <a href='#'>link</a> to the announcement.",
#     "AFK for 10 minutes... need a break ⏳",
#     "YOLO!!! let’s go on that <u>road trip</u> 🚗"
# ]

In [77]:
def removeChatWords(text):
  new_text = []
  patternText = re.compile('\w+|[^\w\s]')
     # to get (words) and (not words or not spaces i.e. special symbols) as separate tokens
  newText = patternText.findall(text)
  for w in newText:
  # for w in text.split():
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)
  return " ".join(new_text)

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-3921816821.py:3: SyntaxWarning: invalid escape sequence '\w'
  patternText = re.compile('\w+|[^\w\s]')

In [78]:
df

,review,filtered_review,lower_case_filtered_review
0,Imprisoned in the 1940s for the double murder ...,Imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...
1,"Spanning the years 1945 to 1955, a chronicle o...","Spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o..."
2,In the continuing saga of the Corleone crime f...,In the continuing saga of the Corleone crime f...,in the continuing saga of the corleone crime f...
3,The true story of how businessman Oskar Schind...,The true story of how businessman Oskar Schind...,the true story of how businessman oskar schind...
4,The defense and the prosecution have rested an...,The defense and the prosecution have rested an...,the defense and the prosecution have rested an...
...,...,...,...
95,"Set in the 22nd century, The Matrix tells the ...","Set in the 22nd century, The Matrix tells the ...","set in the 22nd century, the matrix tells the ..."
96,The invasion of a village in Byelorussia by Ge...,The invasion of a village in Byelorussia by Ge...,the invasion of a village in byelorussia by ge...
97,"Roberto, a shy law student in Rome, meets Brun...","Roberto, a shy law student in Rome, meets Brun...","roberto, a shy law student in rome, meets brun..."
98,"Tony Lip, a bouncer in 1962, is hired to drive...","Tony Lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive..."
99,A peculiar neighbor offers hope to a recent wi...,A peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...

In [79]:
df['lower_case_filtered_review']

0     imprisoned in the 1940s for the double murder ...
1     spanning the years 1945 to 1955, a chronicle o...
2     in the continuing saga of the corleone crime f...
3     the true story of how businessman oskar schind...
4     the defense and the prosecution have rested an...
                            ...
95    set in the 22nd century, the matrix tells the ...
96    the invasion of a village in byelorussia by ge...
97    roberto, a shy law student in rome, meets brun...
98    tony lip, a bouncer in 1962, is hired to drive...
99    a peculiar neighbor offers hope to a recent wi...
Name: lower_case_filtered_review, Length: 100, dtype: object

In [80]:
# import re
# import pandas as pd
# df = pd.DataFrame()
# print(type(df))
# df['sentences'] = sentences
# df
# df['sentencesNoChatWords'] = df['sentences'].apply(removeChatWords)
df['sentencesNoChatWords'] = df['lower_case_filtered_review'].apply(removeChatWords)
df

,review,filtered_review,lower_case_filtered_review,sentencesNoChatWords
0,Imprisoned in the 1940s for the double murder ...,Imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...
1,"Spanning the years 1945 to 1955, a chronicle o...","Spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955 , a chronicle ..."
2,In the continuing saga of the Corleone crime f...,In the continuing saga of the Corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...
3,The true story of how businessman Oskar Schind...,The true story of how businessman Oskar Schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...
4,The defense and the prosecution have rested an...,The defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...
...,...,...,...,...
95,"Set in the 22nd century, The Matrix tells the ...","Set in the 22nd century, The Matrix tells the ...","set in the 22nd century, the matrix tells the ...","set in the 22nd century , the matrix tells the..."
96,The invasion of a village in Byelorussia by Ge...,The invasion of a village in Byelorussia by Ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...
97,"Roberto, a shy law student in Rome, meets Brun...","Roberto, a shy law student in Rome, meets Brun...","roberto, a shy law student in rome, meets brun...","roberto , a shy law student in rome , meets br..."
98,"Tony Lip, a bouncer in 1962, is hired to drive...","Tony Lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...","tony lip , a bouncer in 1962 , is hired to dri..."
99,A peculiar neighbor offers hope to a recent wi...,A peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...

In [81]:
# a = 'LOL that meme was too funny 😂'
# b = removeChatWords(a)
# print(a)
# print(b)
# # c = str(b)
# # print(c)
# c = " ".join(b)
# print(c)

# *Upto now Removal*


## html tag

## punctuation

## chatword

In [82]:
df = df.drop(['sentencesNoChatWords'], axis=1)

In [83]:
df

,review,filtered_review,lower_case_filtered_review
0,Imprisoned in the 1940s for the double murder ...,Imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...
1,"Spanning the years 1945 to 1955, a chronicle o...","Spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o..."
2,In the continuing saga of the Corleone crime f...,In the continuing saga of the Corleone crime f...,in the continuing saga of the corleone crime f...
3,The true story of how businessman Oskar Schind...,The true story of how businessman Oskar Schind...,the true story of how businessman oskar schind...
4,The defense and the prosecution have rested an...,The defense and the prosecution have rested an...,the defense and the prosecution have rested an...
...,...,...,...
95,"Set in the 22nd century, The Matrix tells the ...","Set in the 22nd century, The Matrix tells the ...","set in the 22nd century, the matrix tells the ..."
96,The invasion of a village in Byelorussia by Ge...,The invasion of a village in Byelorussia by Ge...,the invasion of a village in byelorussia by ge...
97,"Roberto, a shy law student in Rome, meets Brun...","Roberto, a shy law student in Rome, meets Brun...","roberto, a shy law student in rome, meets brun..."
98,"Tony Lip, a bouncer in 1962, is hired to drive...","Tony Lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive..."
99,A peculiar neighbor offers hope to a recent wi...,A peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...

In [84]:
# df['noTags'] = df['sentences'].apply(remove_tags)
df['noTags'] = df['lower_case_filtered_review'].apply(remove_tags)
df['lower_case_noTags'] = df['noTags'].apply(lambda x: x.lower())
df['noPunc'] = df['lower_case_noTags'].apply(remove_punc)
df['noChatWords'] = df['noPunc'].apply(removeChatWords)

In [85]:
df

,review,filtered_review,lower_case_filtered_review,noTags,lower_case_noTags,noPunc,noChatWords
0,Imprisoned in the 1940s for the double murder ...,Imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...
1,"Spanning the years 1945 to 1955, a chronicle o...","Spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...",spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...
2,In the continuing saga of the Corleone crime f...,In the continuing saga of the Corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...
3,The true story of how businessman Oskar Schind...,The true story of how businessman Oskar Schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...
4,The defense and the prosecution have rested an...,The defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...
...,...,...,...,...,...,...,...
95,"Set in the 22nd century, The Matrix tells the ...","Set in the 22nd century, The Matrix tells the ...","set in the 22nd century, the matrix tells the ...","set in the 22nd century, the matrix tells the ...","set in the 22nd century, the matrix tells the ...",set in the 22nd century the matrix tells the s...,set in the 22nd century the matrix tells the s...
96,The invasion of a village in Byelorussia by Ge...,The invasion of a village in Byelorussia by Ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...
97,"Roberto, a shy law student in Rome, meets Brun...","Roberto, a shy law student in Rome, meets Brun...","roberto, a shy law student in rome, meets brun...","roberto, a shy law student in rome, meets brun...","roberto, a shy law student in rome, meets brun...",roberto a shy law student in rome meets bruno ...,roberto a shy law student in rome meets bruno ...
98,"Tony Lip, a bouncer in 1962, is hired to drive...","Tony Lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...",tony lip a bouncer in 1962 is hired to drive p...,tony lip a bouncer in 1962 is hired to drive p...
99,A peculiar neighbor offers hope to a recent wi...,A peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...

In [86]:
text = "In My Humble Opinion — that movie was overrated not worth it"
text2 = "!"

# *Spelling Correction*

In [87]:
#Using TEXTBLOB LIBRARY
from textblob import TextBlob
!pip install pyspellchecker
from spellchecker import SpellChecker
    # This one is better it doesn't replace correct old word with new correct word
    # But needsthe punctuations to be spared else it will convert them as well

Requirement already satisfied: pyspellchecker in /usr/local/lib/python3.12/dist-packages (0.8.3)

In [88]:
def noSpellErrors(text):
  spellCorrectionObj = TextBlob(text)
  return (spellCorrectionObj.correct().string)
def noSpellErrors2(text):
  # To generate tokens from the text for pyspellChecker the iterable is required
  tokenSyntax = re.compile('\w+|[^\w\s]')
  tokens = tokenSyntax.findall(text)
  # Creating SpellChecker object
  obj = SpellChecker()
  correctTokens = []
  for token in tokens:
    # Sparing the words present in the
        # spellchecker library and the punctuation set
    if token in obj or punc:
      correctTokens.append(token)
    else:
      correctTokens.append(obj.correction(token))
  return " ".join(correctTokens)

<>:6: SyntaxWarning: invalid escape sequence '\w'
<>:6: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-248078726.py:6: SyntaxWarning: invalid escape sequence '\w'
  tokenSyntax = re.compile('\w+|[^\w\s]')

In [89]:
print(noSpellErrors2(text))

In My Humble Opinion — that movie was overrated not worth it

In [97]:
# df = df.drop(['noSpellErrors2','noSpellErrors2'], axis=1)
# df.drop(['noSpellErrors_Blob','noSpellErrors_SpellChecker'], axis = 1)
import time
startTime = time.time()
df['noSpellErrors_Blob'] = df['noChatWords'].apply(lambda x: x.lower()).apply(noSpellErrors)
df['noSpellErrors_SpellChecker'] = df['noChatWords'].apply(lambda x: x.lower()).apply(noSpellErrors2)
endTime = time.time()
print(endTime-startTime)

88.2035481929779

In [98]:
print(f"Then for the 9980 rows time will be {(endTime-startTime)/100*9980/60}min")

Then for the 9980 rows time will be 146.71190182765324min

In [100]:
df

,review,filtered_review,lower_case_filtered_review,noTags,lower_case_noTags,noPunc,noChatWords,noSpellErrors_Blob,noSpellErrors_SpellChecker
0,Imprisoned in the 1940s for the double murder ...,Imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...
1,"Spanning the years 1945 to 1955, a chronicle o...","Spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...",spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...
2,In the continuing saga of the Corleone crime f...,In the continuing saga of the Corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing sage of the corleone crime f...,in the continuing saga of the corleone crime f...
3,The true story of how businessman Oskar Schind...,The true story of how businessman Oskar Schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oscar schind...,the true story of how businessman oskar schind...
4,The defense and the prosecution have rested an...,The defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...
...,...,...,...,...,...,...,...,...,...
95,"Set in the 22nd century, The Matrix tells the ...","Set in the 22nd century, The Matrix tells the ...","set in the 22nd century, the matrix tells the ...","set in the 22nd century, the matrix tells the ...","set in the 22nd century, the matrix tells the ...",set in the 22nd century the matrix tells the s...,set in the 22nd century the matrix tells the s...,set in the and century the matrix tells the st...,set in the 22nd century the matrix tells the s...
96,The invasion of a village in Byelorussia by Ge...,The invasion of a village in Byelorussia by Ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...
97,"Roberto, a shy law student in Rome, meets Brun...","Roberto, a shy law student in Rome, meets Brun...","roberto, a shy law student in rome, meets brun...","roberto, a shy law student in rome, meets brun...","roberto, a shy law student in rome, meets brun...",roberto a shy law student in rome meets bruno ...,roberto a shy law student in rome meets bruno ...,robert a shy law student in rome meets brunn a...,roberto a shy law student in rome meets bruno ...
98,"Tony Lip, a bouncer in 1962, is hired to drive...","Tony Lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...",tony lip a bouncer in 1962 is hired to drive p...,tony lip a bouncer in 1962 is hired to drive p...,tony lip a bounce in 1962 is hired to drive pi...,tony lip a bouncer in 1962 is hired to drive p...
99,A peculiar neighbor offers hope to a recent wi...,A peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...

# *STOP WORDS REMOVAL*

In [101]:
# I am commenting this entire section of stop words removal for the pos tagging purpose by just the df updation commenting

In [102]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [103]:
from nltk.corpus import stopwords

In [104]:
stopWords = stopwords.words('english')
# print(stopWords)
## Punctuation removal already done not needed
## | Even if needed if would be covered nonetheless
# import string
# punc = string.punctuation

In [105]:
def removeStopWords(text):
  ## This commented section was supposed to be not needed
  ## since we have the punctuation already removed
  ## but remember it will remove any pronouns and such which may be
  ## important for the pos tagging
  patObj = re.compile('[\w\']+|[^\w\s]')
  tokens = patObj.findall(text)
  newText = []
  for words in tokens:
  # for words in text.split():
    if words not in stopWords:
      newText.append(words)
  # print(newText)
  return  " ".join(newText)
  # return newText

<>:6: SyntaxWarning: invalid escape sequence '\w'
<>:6: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-2721029128.py:6: SyntaxWarning: invalid escape sequence '\w'
  patObj = re.compile('[\w\']+|[^\w\s]')

In [106]:
text = "Send, me the details in a Direct PH.D. Message for New York" # the New and York won't be tokenized as one
print(removeStopWords(text))

Send , details Direct PH . D . Message New York

In [107]:
## i am test pos tagging so commented
# df['noStopWords'] = df['noSpellErrors_SpellChecker'].apply(removeStopWords)

In [108]:
df

,review,filtered_review,lower_case_filtered_review,noTags,lower_case_noTags,noPunc,noChatWords,noSpellErrors_Blob,noSpellErrors_SpellChecker
0,Imprisoned in the 1940s for the double murder ...,Imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...
1,"Spanning the years 1945 to 1955, a chronicle o...","Spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...",spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...
2,In the continuing saga of the Corleone crime f...,In the continuing saga of the Corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing sage of the corleone crime f...,in the continuing saga of the corleone crime f...
3,The true story of how businessman Oskar Schind...,The true story of how businessman Oskar Schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oscar schind...,the true story of how businessman oskar schind...
4,The defense and the prosecution have rested an...,The defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...
...,...,...,...,...,...,...,...,...,...
95,"Set in the 22nd century, The Matrix tells the ...","Set in the 22nd century, The Matrix tells the ...","set in the 22nd century, the matrix tells the ...","set in the 22nd century, the matrix tells the ...","set in the 22nd century, the matrix tells the ...",set in the 22nd century the matrix tells the s...,set in the 22nd century the matrix tells the s...,set in the and century the matrix tells the st...,set in the 22nd century the matrix tells the s...
96,The invasion of a village in Byelorussia by Ge...,The invasion of a village in Byelorussia by Ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...
97,"Roberto, a shy law student in Rome, meets Brun...","Roberto, a shy law student in Rome, meets Brun...","roberto, a shy law student in rome, meets brun...","roberto, a shy law student in rome, meets brun...","roberto, a shy law student in rome, meets brun...",roberto a shy law student in rome meets bruno ...,roberto a shy law student in rome meets bruno ...,robert a shy law student in rome meets brunn a...,roberto a shy law student in rome meets bruno ...
98,"Tony Lip, a bouncer in 1962, is hired to drive...","Tony Lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...",tony lip a bouncer in 1962 is hired to drive p...,tony lip a bouncer in 1962 is hired to drive p...,tony lip a bounce in 1962 is hired to drive pi...,tony lip a bouncer in 1962 is hired to drive p...
99,A peculiar neighbor offers hope to a recent wi...,A peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...

# *EMOJI REMOVAL*

In [109]:
## THE PATTERN SECTION IS ONLY COPIED FROM CHATGPT NOTHING ELSE
## SINCE IT'S A STANDARD
def emojiRemove(text):
  emoji_pattern = re.compile(
      "["
      "\U0001F600-\U0001F64F"  # Emoticons
      "\U0001F300-\U0001F5FF"  # Symbols & pictographs
      "\U0001F680-\U0001F6FF"  # Transport & map symbols
      "\U0001F1E0-\U0001F1FF"  # Flags
      "\U00002702-\U000027B0"  # Dingbats
      "\U000024C2-\U0001F251"  # Enclosed characters
      "]+",
      flags=re.UNICODE)
  return emoji_pattern.sub('',text)

In [110]:
!pip install emoji

Collecting emoji
  Downloading emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.14.1-py3-none-any.whl (590 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 590.6/590.6 kB 13.1 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.14.1

In [111]:
import emoji
def emojiReplace(text):
  return emoji.demojize(text)

In [112]:
## Testing the pos tagging hence commented
# df['noEmoji'] = df['noStopWords'].apply(emojiRemove)
# df['emojiMeaning'] = df['noStopWords'].apply(emojiReplace)

df['noEmoji'] = df['noSpellErrors_SpellChecker'].apply(emojiRemove)
df['emojiMeaning'] = df['noSpellErrors_SpellChecker'].apply(emojiReplace)

In [113]:
df

,review,filtered_review,lower_case_filtered_review,noTags,lower_case_noTags,noPunc,noChatWords,noSpellErrors_Blob,noSpellErrors_SpellChecker,noEmoji,emojiMeaning
0,Imprisoned in the 1940s for the double murder ...,Imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...
1,"Spanning the years 1945 to 1955, a chronicle o...","Spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...",spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...
2,In the continuing saga of the Corleone crime f...,In the continuing saga of the Corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing sage of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...
3,The true story of how businessman Oskar Schind...,The true story of how businessman Oskar Schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oscar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...
4,The defense and the prosecution have rested an...,The defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...
...,...,...,...,...,...,...,...,...,...,...,...
95,"Set in the 22nd century, The Matrix tells the ...","Set in the 22nd century, The Matrix tells the ...","set in the 22nd century, the matrix tells the ...","set in the 22nd century, the matrix tells the ...","set in the 22nd century, the matrix tells the ...",set in the 22nd century the matrix tells the s...,set in the 22nd century the matrix tells the s...,set in the and century the matrix tells the st...,set in the 22nd century the matrix tells the s...,set in the 22nd century the matrix tells the s...,set in the 22nd century the matrix tells the s...
96,The invasion of a village in Byelorussia by Ge...,The invasion of a village in Byelorussia by Ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...
97,"Roberto, a shy law student in Rome, meets Brun...","Roberto, a shy law student in Rome, meets Brun...","roberto, a shy law student in rome, meets brun...","roberto, a shy law student in rome, meets brun...","roberto, a shy law student in rome, meets brun...",roberto a shy law student in rome meets bruno ...,roberto a shy law student in rome meets bruno ...,robert a shy law student in rome meets brunn a...,roberto a shy law student in rome meets bruno ...,roberto a shy law student in rome meets bruno ...,roberto a shy law student in rome meets bruno ...
98,"Tony Lip, a bouncer in 1962, is hired to drive...","Tony Lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...",tony lip a bouncer in 1962 is hired to drive p...,tony lip a bouncer in 1962 is hired to drive p...,tony lip a bounce in 1962 is hired to drive pi...,tony lip a bouncer in 1962 is hired to drive p...,tony lip a bouncer in 1962 is hired to drive p...,tony lip a bouncer in 1962 is hired to drive p...
99,A peculiar neighbor offers hope to a recent wi...,A peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...

# *Tokenization*

In [114]:
# .split('.') function
# regex
# nltk
# spacy ## this is the best

In [115]:
import spacy

In [116]:
dictionary = spacy.load('en_core_web_sm')

In [117]:
def tokenizeWordLevel(text):
  tokens = dictionary(text)
  out = []
  for token in tokens:
    out.append(str(token))
  return out
def tokenizeSentenceLevel(text):
  tokens = tokenizeWordLevel(text)
  # print(tokens)
  sentence = []
  out_list = []
  for token in tokens:
    # print(type(token))
    # token = str(token)
        # since we will get string's list from the tokenizeWordLevel
        # no need to convert for comparision
    if token == '.':
      out_list.append(" ".join(sentence))
      sentence = []
    else:
      sentence.append(token)
  return out_list

In [118]:
text = "Send, me the details in a Direct Ph.D. Message for New York. This is my country my Nation. I am GOD Dipesh Shrestha."
output = tokenizeWordLevel(text)
output2 = tokenizeSentenceLevel(text)

print(output)
print(output2)

['Send', ',', 'me', 'the', 'details', 'in', 'a', 'Direct', 'Ph.D.', 'Message', 'for', 'New', 'York', '.', 'This', 'is', 'my', 'country', 'my', 'Nation', '.', 'I', 'am', 'GOD', 'Dipesh', 'Shrestha', '.']
['Send , me the details in a Direct Ph.D. Message for New York', 'This is my country my Nation', 'I am GOD Dipesh Shrestha']

# *Stemming and Lemmatization*

In [119]:
# !pip install nltk
import nltk

In [120]:
# STEMMING
from nltk.stem.porter import PorterStemmer
psObj = PorterStemmer()
def stemmer(text):
  tokens = tokenizeWordLevel(text)
  output = []
  for token in tokens:
    output.append(psObj.stem(token))
  return " ".join(output)

In [121]:
# tokenizeWordLevel(text)
stemmer("I am GOD")

'i am god'

In [122]:
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

True

In [123]:
# LEMMATIZATION
  # Note needs to be in lower case to work properly
from nltk.stem import WordNetLemmatizer
wnlObj = WordNetLemmatizer()
def posLabelForLemmatize(pos):
  if pos.startswith('J'): # adjective
    return 'a'
  elif pos.startswith('V'): # verb
    return 'v'
  elif pos.startswith('N'): # noun
    return 'n'
  elif pos.startswith('R'): # adverb
    return 'r'
  else:
    return 'n'
def lemmatizer(text):
  tokens = tokenizeWordLevel(text)
  # print(tokens)
  token_pos_list = nltk.pos_tag(tokens)
  output = []
  for token, pos in token_pos_list:
    # print(pos)
    output.append(wnlObj.lemmatize(token, pos= posLabelForLemmatize(pos)))
  return " ".join(output)

In [124]:
##
  # Note needs to be in lower case for lemmatize to work properly
# print(wnlObj.lemmatize("running", pos = 'v'))
# print(wnlObj.lemmatize("Running",pos = 'v'))

# lemmatizer("laughing")
# a = nltk.pos_tag(["GOD"])
# print(a) #[('GOD', 'NNP')]
# pos_tags = nltk.pos_tag(["GOD"])
# type(pos_tags)
# print(pos_tags)

In [125]:
df['stemmed'] = df['noEmoji'].apply(stemmer)
df['lemmatized'] = df['noEmoji'].apply(lemmatizer)

In [126]:
df

,review,filtered_review,lower_case_filtered_review,noTags,lower_case_noTags,noPunc,noChatWords,noSpellErrors_Blob,noSpellErrors_SpellChecker,noEmoji,emojiMeaning,stemmed,lemmatized
0,Imprisoned in the 1940s for the double murder ...,Imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprisoned in the 1940s for the double murder ...,imprison in the 1940 for the doubl murder of h...,imprison in the 1940s for the double murder of...
1,"Spanning the years 1945 to 1955, a chronicle o...","Spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...","spanning the years 1945 to 1955, a chronicle o...",spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,spanning the years 1945 to 1955 a chronicle of...,span the year 1945 to 1955 a chronicl of the f...,span the year 1945 to 1955 a chronicle of the ...
2,In the continuing saga of the Corleone crime f...,In the continuing saga of the Corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing sage of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continuing saga of the corleone crime f...,in the continu saga of the corleon crime famil...,in the continue saga of the corleone crime fam...
3,The true story of how businessman Oskar Schind...,The true story of how businessman Oskar Schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oscar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true story of how businessman oskar schind...,the true stori of how businessman oskar schind...,the true story of how businessman oskar schind...
4,The defense and the prosecution have rested an...,The defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defense and the prosecution have rested an...,the defens and the prosecut have rest and the ...,the defense and the prosecution have rest and ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"Set in the 22nd century, The Matrix tells the ...","Set in the 22nd century, The Matrix tells the ...","set in the 22nd century, the matrix tells the ...","set in the 22nd century, the matrix tells the ...","set in the 22nd century, the matrix tells the ...",set in the 22nd century the matrix tells the s...,set in the 22nd century the matrix tells the s...,set in the and century the matrix tells the st...,set in the 22nd century the matrix tells the s...,set in the 22nd century the matrix tells the s...,set in the 22nd century the matrix tells the s...,set in the 22nd centuri the matrix tell the st...,set in the 22nd century the matrix tell the st...
96,The invasion of a village in Byelorussia by Ge...,The invasion of a village in Byelorussia by Ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invasion of a village in byelorussia by ge...,the invas of a villag in byelorussia by german...,the invasion of a village in byelorussia by ge...
97,"Roberto, a shy law student in Rome, meets Brun...","Roberto, a shy law student in Rome, meets Brun...","roberto, a shy law student in rome, meets brun...","roberto, a shy law student in rome, meets brun...","roberto, a shy law student in rome, meets brun...",roberto a shy law student in rome meets bruno ...,roberto a shy law student in rome meets bruno ...,robert a shy law student in rome meets brunn a...,roberto a shy law student in rome meets bruno ...,roberto a shy law student in rome meets bruno ...,roberto a shy law student in rome meets bruno ...,roberto a shi law student in rome meet bruno a...,roberto a shy law student in rome meet bruno a...
98,"Tony Lip, a bouncer in 1962, is hired to drive...","Tony Lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...","tony lip, a bouncer in 1962, is hired to drive...",tony lip a bouncer in 1962 is hired to drive p...,tony lip a bouncer in 1962 is hired to drive p...,tony lip a bounce in 1962 is hired to drive pi...,tony lip a bouncer in 1962 is hired to drive p...,tony lip a bouncer in 1962 is hired to drive p...,tony lip a bouncer in 1962 is hired to drive p...,toni lip a bouncer in 1962 is hire to drive pi...,tony lip a bouncer in 1962 be hire to drive pi...
99,A peculiar neighbor offers hope to a recent wi...,A peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offers hope to a recent wi...,a peculiar neighbor offer hope to a recent wid...,a peculiar neighbor offer hope to a recent wid...