# *DATA IMPORTS*

In [32]:
import pandas as pd

In [33]:
dfNew = pd.read_csv('/content/drive/MyDrive/WebScrapedCSVs/movies.csv')

In [34]:
df = pd.DataFrame({})
df['overview'] = dfNew['overview'].iloc[:100]
df['overview'] = df['overview'].fillna('')
df['overview'].head()

0    Imprisoned in the 1940s for the double murder ...
1    Spanning the years 1945 to 1955, a chronicle o...
2    In the continuing saga of the Corleone crime f...
3    The true story of how businessman Oskar Schind...
4    The defense and the prosecution have rested an...
Name: overview, dtype: object

# *OHE*

In [85]:
# OHE requires categorical variable

In [86]:
# 100 categorical values from ChatGPT
data = [
    "apple","orange","banana","apple","banana","orange","orange","apple","banana","orange",
    "apple","apple","banana","orange","apple","banana","orange","banana","apple","orange",
    "banana","apple","orange","orange","banana","apple","orange","banana","orange","apple",
    "banana","apple","orange","banana","apple","orange","apple","banana","orange","banana",
    "apple","orange","apple","banana","orange","apple","banana","orange","apple","apple",
    "banana","orange","banana","apple","orange","apple","banana","orange","banana","apple",
    "apple","orange","banana","apple","orange","banana","apple","orange","banana","orange",
    "apple","banana","apple","orange","banana","apple","orange","orange","banana","apple",
    "banana","orange","apple","orange","apple","banana","orange","apple","banana","apple",
    "orange","banana","apple","orange","banana","orange","apple","banana","apple","orange"
]

In [87]:
df['fruits'] = data
df.head()

                                            overview  fruits
0  Imprisoned in the 1940s for the double murder ...   apple
1  Spanning the years 1945 to 1955, a chronicle o...  orange
2  In the continuing saga of the Corleone crime f...  banana
3  The true story of how businessman Oskar Schind...   apple
4  The defense and the prosecution have rested an...  banana

In [92]:
from sklearn.preprocessing import OneHotEncoder
oheObj = OneHotEncoder()
ohevectors = oheObj.fit_transform(df[['fruits']])
dfFruits = pd.DataFrame(
    ohevectors.toarray(),
    columns = oheObj.get_feature_names_out()
)
dfFinal = pd.concat([df, dfFruits], axis=1)
dfFinal

                                             overview  ... fruits_orange
0   Imprisoned in the 1940s for the double murder ...  ...           0.0
1   Spanning the years 1945 to 1955, a chronicle o...  ...           1.0
2   In the continuing saga of the Corleone crime f...  ...           0.0
3   The true story of how businessman Oskar Schind...  ...           0.0
4   The defense and the prosecution have rested an...  ...           0.0
..                                                ...  ...           ...
95  Set in the 22nd century, The Matrix tells the ...  ...           1.0
96  The invasion of a village in Byelorussia by Ge...  ...           0.0
97  Roberto, a shy law student in Rome, meets Brun...  ...           0.0
98  Tony Lip, a bouncer in 1962, is hired to drive...  ...           0.0
99  A peculiar neighbor offers hope to a recent wi...  ...           1.0

[100 rows x 5 columns]

# *BAG OF WORDS*

In [35]:
from sklearn.feature_extraction.text import CountVectorizer

In [54]:
cvObj = CountVectorizer(max_features=100)
      # THE max_features means the top 100 words
      # with most frequency from the vocabulary
      # are to be used for creating bow vectors
bow = cvObj.fit_transform(df['overview'])

In [55]:
print((bow[0]).shape)
bow[0].toarray()

(1, 100)

array([[0, 0, 0, 2, 2, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 1, 0, 4, 0, 2, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]])

In [56]:
len(cvObj.vocabulary_)

100

# *N-Gram*

In [62]:
## BIGRAM
cvObj2 = CountVectorizer(ngram_range=(2,2), max_features=100)
bigrams = cvObj2.fit_transform(df['overview'])
cvObj2.vocabulary_

{'in the': np.int64(39),
 'for the': np.int64(26),
 'of his': np.int64(44),
 'new life': np.int64(42),
 'at the': np.int64(9),
 'where he': np.int64(87),
 'for an': np.int64(24),
 'to be': np.int64(72),
 'by the': np.int64(17),
 'the other': np.int64(61),
 'for his': np.int64(25),
 'of the': np.int64(45),
 'crime family': np.int64(18),
 'on his': np.int64(46),
 'his life': np.int64(35),
 'to take': np.int64(78),
 'up in': np.int64(83),
 'the true': np.int64(66),
 'true story': np.int64(81),
 'story of': np.int64(55),
 'from the': np.int64(28),
 'in his': np.int64(38),
 'world war': np.int64(98),
 'war ii': np.int64(84),
 'and the': np.int64(2),
 'into the': np.int64(40),
 'as an': np.int64(4),
 'each other': np.int64(21),
 'with the': np.int64(95),
 'the help': np.int64(59),
 'help of': np.int64(32),
 'sets out': np.int64(53),
 'out to': np.int64(51),
 'to the': np.int64(79),
 'as the': np.int64(6),
 'at his': np.int64(8),
 'under the': np.int64(82),
 'of her': np.int64(43),
 'when the': np.int64(86),
 'he tries': np.int64(31),
 'to help': np.int64(75),
 'in an': np.int64(37),
 'the fate': np.int64(57),
 'fate of': np.int64(23),
 'the world': np.int64(70),
 'the fellowship': np.int64(58),
 'the ring': np.int64(62),
 'by his': np.int64(16),
 'to destroy': np.int64(73),
 'destroy the': np.int64(19),
 'the two': np.int64(67),
 'group of': np.int64(29),
 'who is': np.int64(89),
 'at an': np.int64(7),
 'year old': np.int64(99),
 'and his': np.int64(1),
 'with their': np.int64(96),
 'with no': np.int64(94),
 'and their': np.int64(3),
 'who lives': np.int64(90),
 'his own': np.int64(36),
 'when his': np.int64(85),
 'his entire': np.int64(33),
 'tries to': np.int64(80),
 'the way': np.int64(69),
 'out of': np.int64(50),
 'after the': np.int64(0),
 'to find': np.int64(74),
 'from his': np.int64(27),
 'order to': np.int64(49),
 'to protect': np.int64(77),
 'protect the': np.int64(52),
 'be destroyed': np.int64(10),
 'on the': np.int64(47),
 'as he': np.int64(5),
 'on their': np.int64(48),
 'the one': np.int64(60),
 'but on': np.int64(13),
 'within the': np.int64(97),
 'betrayal and': np.int64(11),
 'starts to': np.int64(54),
 'by an': np.int64(15),
 'his family': np.int64(34),
 'the war': np.int64(68),
 'break through': np.int64(12),
 'window and': np.int64(91),
 'may be': np.int64(41),
 'but when': np.int64(14),
 'with dreams': np.int64(92),
 'the same': np.int64(63),
 'who has': np.int64(88),
 'the story': np.int64(65),
 'with his': np.int64(93),
 'due to': np.int64(20),
 'to make': np.int64(76),
 'through the': np.int64(71),
 'entire life': np.int64(22),
 'he is': np.int64(30),
 'the ship': np.int64(64),
 'the avengers': np.int64(56)}

In [64]:
# BOTH UNIGRAM AND BIGRAM
cvObj2 = CountVectorizer(ngram_range=(1,2), max_features=100)
bigrams = cvObj2.fit_transform(df['overview'])
cvObj2.vocabulary_

{'in': np.int64(34),
 'the': np.int64(69),
 'for': np.int64(22),
 'of': np.int64(48),
 'his': np.int64(33),
 'and': np.int64(3),
 'her': np.int64(31),
 'new': np.int64(47),
 'life': np.int64(40),
 'at': np.int64(8),
 'prison': np.int64(60),
 'where': np.int64(89),
 'he': np.int64(29),
 'to': np.int64(77),
 'an': np.int64(2),
 'during': np.int64(17),
 'be': np.int64(11),
 'by': np.int64(15),
 'other': np.int64(55),
 'in the': np.int64(36),
 'for the': np.int64(23),
 'of his': np.int64(49),
 'at the': np.int64(9),
 'to be': np.int64(78),
 'the other': np.int64(70),
 'years': np.int64(98),
 'crime': np.int64(16),
 'family': np.int64(19),
 'when': np.int64(88),
 'on': np.int64(52),
 'of the': np.int64(50),
 'on his': np.int64(53),
 'young': np.int64(99),
 'up': np.int64(84),
 'into': np.int64(37),
 'story': np.int64(65),
 'over': np.int64(57),
 'lives': np.int64(41),
 'from': np.int64(24),
 'while': np.int64(90),
 'they': np.int64(73),
 'as': np.int64(6),
 'world': np.int64(95),
 'war': np.int64(85),
 'story of': np.int64(66),
 'from the': np.int64(25),
 'in his': np.int64(35),
 'have': np.int64(28),
 'is': np.int64(38),
 'what': np.int64(87),
 'becomes': np.int64(12),
 'each': np.int64(18),
 'and the': np.int64(4),
 'girl': np.int64(26),
 'she': np.int64(63),
 'must': np.int64(45),
 'never': np.int64(46),
 'with': np.int64(93),
 'help': np.int64(30),
 'out': np.int64(56),
 'that': np.int64(68),
 'but': np.int64(14),
 'find': np.int64(20),
 'with the': np.int64(94),
 'to the': np.int64(79),
 'as the': np.int64(7),
 'who': np.int64(91),
 'has': np.int64(27),
 'love': np.int64(42),
 'under': np.int64(83),
 'people': np.int64(59),
 'tries': np.int64(81),
 'man': np.int64(44),
 'all': np.int64(1),
 'takes': np.int64(67),
 'their': np.int64(71),
 'one': np.int64(54),
 'ring': np.int64(61),
 'this': np.int64(74),
 'time': np.int64(76),
 'are': np.int64(5),
 'two': np.int64(82),
 'him': np.int64(32),
 'make': np.int64(43),
 'who is': np.int64(92),
 'after': np.int64(0),
 'town': np.int64(80),
 'year': np.int64(96),
 'old': np.int64(51),
 'year old': np.int64(97),
 'own': np.int64(58),
 'way': np.int64(86),
 'finds': np.int64(21),
 'it': np.int64(39),
 'before': np.int64(13),
 'school': np.int64(62),
 'spider': np.int64(64),
 'through': np.int64(75),
 'them': np.int64(72),
 'band': np.int64(10)}

# *TF-IDF*

In [98]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfObj = TfidfVectorizer(max_features =100)
tfidfVectors = tfidfObj.fit_transform(df['overview'])
print(tfidfVectors.toarray())

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.21963015 0.        ]
 [0.         0.         0.         ... 0.         0.         0.14877424]
 ...
 [0.         0.         0.         ... 0.25046708 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

# *Final Practice*

In [136]:
# OHE
df['fruits']
from sklearn.preprocessing import OneHotEncoder
oheObj = OneHotEncoder()
oheVectors = oheObj.fit_transform(df[['fruits']])
oheVectors.toarray()
dfnew = pd.DataFrame(
    oheVectors.toarray(),
    columns = oheObj.get_feature_names_out()
)
dffinal = pd.concat([df, dfnew], axis=1)
dffinal

# ngram
from sklearn.feature_extraction.text import CountVectorizer
cvObj = CountVectorizer(ngram_range=(1,3), max_features =5)
cvVectors = cvObj.fit_transform(df['overview'])
cvVectors.toarray()
dffinal['1-3-Grams'] = str(cvVectors.toarray())
dfnew = pd.DataFrame(
    cvVectors.toarray(),
    columns = cvObj.get_feature_names_out()
)
dffinal2 = pd.concat([dffinal, dfnew],axis=1)
dffinal2

# tfidf
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfObj = TfidfVectorizer(max_features=3)
tfidfVectors = tfidfObj.fit_transform(df['overview'])
dffinal2['tfidf'] = str(tfidfVectors.toarray())
dffinal2
dfnew = pd.DataFrame(
    tfidfVectors.toarray(),
    columns = tfidfObj.get_feature_names_out()
)
tfidfObj.get_feature_names_out().shape
dffinal3 = pd.concat([dffinal2, dfnew], axis=1)
dffinal3

                                             overview  ...        to
0   Imprisoned in the 1940s for the double murder ...  ...  0.449205
1   Spanning the years 1945 to 1955, a chronicle o...  ...  0.605483
2   In the continuing saga of the Corleone crime f...  ...  0.243808
3   The true story of how businessman Oskar Schind...  ...  0.000000
4   The defense and the prosecution have rested an...  ...  0.128318
..                                                ...  ...       ...
95  Set in the 22nd century, The Matrix tells the ...  ...  0.000000
96  The invasion of a village in Byelorussia by Ge...  ...  0.449205
97  Roberto, a shy law student in Rome, meets Brun...  ...  0.337194
98  Tony Lip, a bouncer in 1962, is hired to drive...  ...  0.637143
99  A peculiar neighbor offers hope to a recent wi...  ...  0.904959

[100 rows x 15 columns]