IMPORTING PANDAS

In [2]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/Fortune500_Cleaned.csv')

In [3]:
df.head()

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,2300000,1.0,485873.0,0.8,13643.0,-7.2,198825.0,218619.0
1,2,Berkshire Hathaway,367700,4.0,223604.0,6.1,24074.0,0.0,620854.0,411035.0
2,3,Apple,116000,3.0,215639.0,-7.7,45687.0,-14.4,321686.0,753718.0
3,4,Exxon Mobil,72700,2.0,205004.0,-16.7,7840.0,-51.5,330314.0,340056.0
4,5,McKesson,68000,5.0,192487.0,6.2,2258.0,53.0,56563.0,31439.0

 Opening A CSV file from an URL

In [5]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/paiv/fci-breeds/main/fci-breeds.csv"

# If the site requires headers (sometimes needed for GitHub raw), you can add them
headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept": "text/csv"
}

response = requests.get(url, headers=headers)

# Now treat the content as CSV text
csv_data = StringIO(response.text)
df2 = pd.read_csv(csv_data)

print(df2.head(5))

   id                    name          group  \
0   1         ENGLISH POINTER  Pointing Dogs
1   2          ENGLISH SETTER  Pointing Dogs
2   3      KERRY BLUE TERRIER       Terriers
3   4           CAIRN TERRIER       Terriers
4   5  ENGLISH COCKER SPANIEL     Retrievers

                                  section provisional        country  \
0  British and Irish Pointers and Setters         NaN  GREAT BRITAIN
1  British and Irish Pointers and Setters         NaN  GREAT BRITAIN
2         Large and medium sized Terriers         NaN        IRELAND
3                    Small sized Terriers         NaN  GREAT BRITAIN
4                           Flushing Dogs         NaN  GREAT BRITAIN

                                                 url  \
0  https://www.fci.be/en/nomenclature/ENGLISH-POI...
1  https://www.fci.be/en/nomenclature/ENGLISH-SET...
2  https://www.fci.be/en/nomenclature/KERRY-BLUE-...
3  https://www.fci.be/en/nomenclature/CAIRN-TERRI...
4  https://www.fci.be/en/nomenclature/ENGLISH-COC...

                                               image  \
0  https://www.fci.be/Nomenclature/Illustrations/...
1  https://www.fci.be/Nomenclature/Illustrations/...
2                                                NaN
3  https://www.fci.be/Nomenclature/Illustrations/...
4  https://www.fci.be/Nomenclature/Illustrations/...

                                                 pdf
0  https://www.fci.be/Nomenclature/Standards/001g...
1  https://www.fci.be/Nomenclature/Standards/002g...
2  https://www.fci.be/Nomenclature/Standards/003g...
3  https://www.fci.be/Nomenclature/Standards/004g...
4  https://www.fci.be/Nomenclature/Standards/005g...

TSV FILE READING WITH SEP PARAMETER

In [11]:
names = [
    'ID', 'Name', 'Age', 'Gender', 'Breed', 'Color', 'Weight', 'Height',
    'DateOfBirth', 'OwnerName', 'Address', 'City', 'State', 'ZipCode', 'PhoneNumber',
    'Email', 'Vaccinated', 'Microchipped', 'SpayedNeutered', 'Allergies', 'MedicalNotes',
    'LastVisitDate', 'NextAppointment', 'InsuranceProvider', 'PolicyNumber',
    'RegistrationDate', 'TrainerName', 'BehaviorNotes', 'FeedingSchedule',
    'ExerciseRoutine', 'FavoriteToy', 'SpecialNeeds'
]

df2 = pd.read_csv('/content/sample-1.tsv', sep='\t', names=names)
df2.head()

,ID,Name,Age,Gender,Breed,Color,Weight,Height,DateOfBirth,OwnerName,...,NextAppointment,InsuranceProvider,PolicyNumber,RegistrationDate,TrainerName,BehaviorNotes,FeedingSchedule,ExerciseRoutine,FavoriteToy,SpecialNeeds
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2022.0,Create more with themes Go to Fo...,NaN,NaN,NaN,NaN,NaN
1,NaN,JANUARY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FEBRUARY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,S,M,T,W,T,F,S,NaN,S,...,F,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,...,4,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,2,3,4,5,6,7,8,NaN,6,...,11,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

INDEX COL PARAMETER

In [12]:
df = pd.read_csv("/content/Fortune500_Cleaned.csv", index_col='Rank')
df.head()

,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
Rank,,,,,,,,,
1,Walmart,2300000,1.0,485873.0,0.8,13643.0,-7.2,198825.0,218619.0
2,Berkshire Hathaway,367700,4.0,223604.0,6.1,24074.0,0.0,620854.0,411035.0
3,Apple,116000,3.0,215639.0,-7.7,45687.0,-14.4,321686.0,753718.0
4,Exxon Mobil,72700,2.0,205004.0,-16.7,7840.0,-51.5,330314.0,340056.0
5,McKesson,68000,5.0,192487.0,6.2,2258.0,53.0,56563.0,31439.0

HEADER PARAMTER

In [13]:
df = pd.read_csv("/content/Fortune500_Cleaned.csv", header=1)
df.head()

,1,Walmart,2300000,1.0,485873.0,0.8,13643.0,-7.2,198825.0,218619.0
0,2,Berkshire Hathaway,367700,4.0,223604.0,6.1,24074.0,0.0,620854.0,411035.0
1,3,Apple,116000,3.0,215639.0,-7.7,45687.0,-14.4,321686.0,753718.0
2,4,Exxon Mobil,72700,2.0,205004.0,-16.7,7840.0,-51.5,330314.0,340056.0
3,5,McKesson,68000,5.0,192487.0,6.2,2258.0,53.0,56563.0,31439.0
4,6,UnitedHealth Group,230000,6.0,184840.0,17.7,7017.0,20.7,122810.0,157793.0

USE_COLS PARAMETER

In [18]:
df = pd.read_csv("/content/Fortune500_Cleaned.csv", usecols=['Rank','Profits','Assets'])
df.head()

   Rank  Profits    Assets
0     1  13643.0  198825.0
1     2  24074.0  620854.0
2     3  45687.0  321686.0
3     4   7840.0  330314.0
4     5   2258.0   56563.0

SKIPROWS PARAMETER

In [36]:
df2 = pd.read_csv("/content/Fortune500_Cleaned.csv",skiprows=[0,2,4])
df2.head(5)

,1,Walmart,2300000,1.0,485873.0,0.8,13643.0,-7.2,198825.0,218619.0
0,3,Apple,116000,3.0,215639.0,-7.7,45687.0,-14.4,321686.0,753718.0
1,5,McKesson,68000,5.0,192487.0,6.2,2258.0,53.0,56563.0,31439.0
2,6,UnitedHealth Group,230000,6.0,184840.0,17.7,7017.0,20.7,122810.0,157793.0
3,7,CVS Health,204000,7.0,177526.0,15.8,5317.0,1.5,94462.0,81310.0
4,8,General Motors,225000,8.0,166380.0,9.2,9427.0,-2.7,221690.0,52968.0

NROWS PARAMETER

In [40]:
df2 = pd.read_csv("/content/Fortune500_Cleaned.csv",nrows=2)
df2.head(5)

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,2300000,1.0,485873.0,0.8,13643.0,-7.2,198825.0,218619.0
1,2,Berkshire Hathaway,367700,4.0,223604.0,6.1,24074.0,0.0,620854.0,411035.0

ENCODING PARAMETER

In [4]:
# df2 = pd.read_csv("/content/Fortune500_Cleaned.csv",nrows=2, encoding='UTF-8')
# df2.head(5)

SKIP BAD LINES

In [8]:
# e.g. some row may have 9 column values but the dataset is of 8 it will help to
# skip those rows
df2 = pd.read_csv("/content/Fortune500_Cleaned.csv",nrows=2, on_bad_lines='skip')
df2.head(5)

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,2300000,1.0,485873.0,0.8,13643.0,-7.2,198825.0,218619.0
1,2,Berkshire Hathaway,367700,4.0,223604.0,6.1,24074.0,0.0,620854.0,411035.0

dtype parameter

In [19]:
# pd.read_csv("/content/Fortune500_Cleaned.csv",nrows=2, on_bad_lines='skip').info()
# pd.read_csv("/content/Fortune500_Cleaned.csv",nrows=2, on_bad_lines='skip').head()
pd.read_csv("/content/Fortune500_Cleaned.csv",dtype={"Market Value":int}).head()

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,2300000,1.0,485873.0,0.8,13643.0,-7.2,198825.0,218619
1,2,Berkshire Hathaway,367700,4.0,223604.0,6.1,24074.0,0.0,620854.0,411035
2,3,Apple,116000,3.0,215639.0,-7.7,45687.0,-14.4,321686.0,753718
3,4,Exxon Mobil,72700,2.0,205004.0,-16.7,7840.0,-51.5,330314.0,340056
4,5,McKesson,68000,5.0,192487.0,6.2,2258.0,53.0,56563.0,31439

HANDLING DATES

In [20]:
# pd.read_csv("/content/Fortune500_Cleaned.csv",parse_dates=['date']).head()

CONVERTORS

In [22]:
def rename(name):
  if name == "Apple":
    return "APPL"
  else:
    return name

pd.read_csv("/content/Fortune500_Cleaned.csv",converters={'Company Name':rename}).head()

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,Walmart,2300000,1.0,485873.0,0.8,13643.0,-7.2,198825.0,218619.0
1,2,Berkshire Hathaway,367700,4.0,223604.0,6.1,24074.0,0.0,620854.0,411035.0
2,3,APPL,116000,3.0,215639.0,-7.7,45687.0,-14.4,321686.0,753718.0
3,4,Exxon Mobil,72700,2.0,205004.0,-16.7,7840.0,-51.5,330314.0,340056.0
4,5,McKesson,68000,5.0,192487.0,6.2,2258.0,53.0,56563.0,31439.0

na_values PARAMETER

In [24]:
# e.g replace certain values as NAN
pd.read_csv("/content/Fortune500_Cleaned.csv",na_values=['Walmart']).head()

,Rank,Company Name,Number of Employees,Previous Rank,Revenues,Revenue Change,Profits,Profit Change,Assets,Market Value
0,1,NaN,2300000,1.0,485873.0,0.8,13643.0,-7.2,198825.0,218619.0
1,2,Berkshire Hathaway,367700,4.0,223604.0,6.1,24074.0,0.0,620854.0,411035.0
2,3,Apple,116000,3.0,215639.0,-7.7,45687.0,-14.4,321686.0,753718.0
3,4,Exxon Mobil,72700,2.0,205004.0,-16.7,7840.0,-51.5,330314.0,340056.0
4,5,McKesson,68000,5.0,192487.0,6.2,2258.0,53.0,56563.0,31439.0

LOADING DATASET IN CHUNKS

In [30]:
df = pd.read_csv("/content/Fortune500_Cleaned.csv",na_values=['Walmart'], chunksize=100)
for chunk in df:
  print(chunk.shape)

(100, 10)
(100, 10)
(100, 10)
(100, 10)
(100, 10)