In [1]:
!pip install optuna

Collecting optuna
  Downloading optuna-4.4.0-py3-none-any.whl.metadata (17 kB)
Collecting alembic>=1.5.0 (from optuna)
  Downloading alembic-1.16.4-py3-none-any.whl.metadata (7.3 kB)
Collecting colorlog (from optuna)
  Downloading colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from optuna) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.11/dist-packages (from optuna) (2.0.41)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from optuna) (4.67.1)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.11/dist-packages (from optuna) (6.0.2)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.11/dist-packages (from alembic>=1.5.0->optuna) (4.14.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.3)
Downloading optuna-4.4.0-py3-none-any.whl (395 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 395.9/395.9 kB 1.5 MB/s eta 0:00:00
Downloading alembic-1.16.4-py3-none-any.whl (247 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.0/247.0 kB 9.8 MB/s eta 0:00:00
Downloading colorlog-6.9.0-py3-none-any.whl (11 kB)
Installing collected packages: colorlog, alembic, optuna
Successfully installed alembic-1.16.4 colorlog-6.9.0 optuna-4.4.0

In [2]:
# Import necessary libraries
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Pima Indian Diabetes dataset from sklearn
# Note: Scikit-learn's built-in 'load_diabetes' is a regression dataset.
# We will load the actual diabetes dataset from an external source
import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [3]:
import numpy as np

# Replace zero values with NaN in columns where zero is not a valid value
cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

# Impute the missing values with the mean of the respective column
df.fillna(df.mean(), inplace=True)

# Check if there are any remaining missing values
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [29]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # trial object is passed when the study.optimize() fxn get triggered
    # Suggest values for the hyperparameters based on the trail object which was
      # tuned by the TPE sampler
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize
          # this is the value being returned to set inside the study object

In [30]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-07-14 10:37:40,712] A new study created in memory with name: no-name-99537fff-f249-4267-b4ae-bd41fbcc2859
[I 2025-07-14 10:37:41,590] Trial 0 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 161, 'max_depth': 20}. Best is trial 0 with value: 0.7709497206703911.
[I 2025-07-14 10:37:41,939] Trial 1 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 90, 'max_depth': 19}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:42,548] Trial 2 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 159, 'max_depth': 14}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:42,772] Trial 3 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 54, 'max_depth': 19}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:43,382] Trial 4 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 163, 'max_depth': 10}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:43,875] Trial 5 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 128, 'max_depth': 9}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:44,314] Trial 6 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 130, 'max_depth': 3}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:44,955] Trial 7 finished with value: 0.756052141527002 and parameters: {'n_estimators': 190, 'max_depth': 3}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:45,640] Trial 8 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 183, 'max_depth': 11}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:45,925] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 72, 'max_depth': 7}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:46,325] Trial 10 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 95, 'max_depth': 16}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:46,536] Trial 11 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 51, 'max_depth': 20}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:46,910] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 92, 'max_depth': 17}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:47,155] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 57, 'max_depth': 17}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:47,489] Trial 14 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 85, 'max_depth': 15}. Best is trial 1 with value: 0.7765363128491621.
[I 2025-07-14 10:37:47,935] Trial 15 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 113, 'max_depth': 19}. Best is trial 15 with value: 0.7783985102420856.
[I 2025-07-14 10:37:48,381] Trial 16 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 112, 'max_depth': 13}. Best is trial 15 with value: 0.7783985102420856.
[I 2025-07-14 10:37:48,830] Trial 17 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 112, 'max_depth': 18}. Best is trial 15 with value: 0.7783985102420856.
[I 2025-07-14 10:37:49,368] Trial 18 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 141, 'max_depth': 13}. Best is trial 15 with value: 0.7783985102420856.
[I 2025-07-14 10:37:49,779] Trial 19 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 111, 'max_depth': 7}. Best is trial 15 with value: 0.7783985102420856.
[I 2025-07-14 10:37:50,084] Trial 20 finished with value: 0.7839851024208566 and parameters: {'n_estimators': 73, 'max_depth': 18}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:50,382] Trial 21 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 75, 'max_depth': 18}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:50,669] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 72, 'max_depth': 16}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:50,975] Trial 23 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 74, 'max_depth': 18}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:51,261] Trial 24 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 71, 'max_depth': 17}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:51,577] Trial 25 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 64, 'max_depth': 15}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:52,077] Trial 26 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 83, 'max_depth': 17}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:52,493] Trial 27 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 65, 'max_depth': 13}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:53,056] Trial 28 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:53,376] Trial 29 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 80, 'max_depth': 20}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:53,790] Trial 30 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 103, 'max_depth': 18}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:54,099] Trial 31 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 76, 'max_depth': 18}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:54,364] Trial 32 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 20}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:54,655] Trial 33 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 72, 'max_depth': 16}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:55,023] Trial 34 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 87, 'max_depth': 18}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:55,265] Trial 35 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 59, 'max_depth': 14}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:55,477] Trial 36 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 51, 'max_depth': 19}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:56,038] Trial 37 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 147, 'max_depth': 19}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:56,315] Trial 38 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 17}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:56,717] Trial 39 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 101, 'max_depth': 14}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:57,023] Trial 40 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 78, 'max_depth': 11}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:57,317] Trial 41 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 17}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:57,689] Trial 42 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 91, 'max_depth': 16}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:57,922] Trial 43 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 58, 'max_depth': 18}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:58,235] Trial 44 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 75, 'max_depth': 20}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:58,522] Trial 45 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 71, 'max_depth': 17}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:59,189] Trial 46 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 178, 'max_depth': 19}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:59,621] Trial 47 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 123, 'max_depth': 4}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:37:59,994] Trial 48 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 96, 'max_depth': 15}. Best is trial 20 with value: 0.7839851024208566.
[I 2025-07-14 10:38:00,357] Trial 49 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 87, 'max_depth': 19}. Best is trial 20 with value: 0.7839851024208566.

In [31]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7839851024208566
Best hyperparameters: {'n_estimators': 73, 'max_depth': 18}

In [32]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

## Samplers in Optuna

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [16]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-07-14 10:32:55,611] A new study created in memory with name: no-name-e90d9d6f-3362-4629-bc3f-77cd7a043ad2
[I 2025-07-14 10:32:56,227] Trial 0 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 156, 'max_depth': 20}. Best is trial 0 with value: 0.7728119180633147.
[I 2025-07-14 10:32:56,475] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 65, 'max_depth': 9}. Best is trial 0 with value: 0.7728119180633147.
[I 2025-07-14 10:32:56,787] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 75, 'max_depth': 16}. Best is trial 0 with value: 0.7728119180633147.
[I 2025-07-14 10:32:57,092] Trial 3 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 78, 'max_depth': 11}. Best is trial 0 with value: 0.7728119180633147.
[I 2025-07-14 10:32:57,444] Trial 4 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 87, 'max_depth': 12}. Best is trial 0 with value: 0.7728119180633147.
[I 2025-07-14 10:32:57,994] Trial 5 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 153, 'max_depth': 5}. Best is trial 0 with value: 0.7728119180633147.
[I 2025-07-14 10:32:58,354] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 90, 'max_depth': 16}. Best is trial 0 with value: 0.7728119180633147.
[I 2025-07-14 10:32:58,899] Trial 7 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 141, 'max_depth': 13}. Best is trial 0 with value: 0.7728119180633147.
[I 2025-07-14 10:32:59,463] Trial 8 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 154, 'max_depth': 7}. Best is trial 8 with value: 0.7765363128491619.
[I 2025-07-14 10:32:59,710] Trial 9 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 18}. Best is trial 8 with value: 0.7765363128491619.
[I 2025-07-14 10:33:00,314] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 155, 'max_depth': 16}. Best is trial 8 with value: 0.7765363128491619.
[I 2025-07-14 10:33:00,864] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 141, 'max_depth': 15}. Best is trial 8 with value: 0.7765363128491619.
[I 2025-07-14 10:33:01,516] Trial 12 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 174, 'max_depth': 8}. Best is trial 8 with value: 0.7765363128491619.
[I 2025-07-14 10:33:02,197] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 175, 'max_depth': 17}. Best is trial 8 with value: 0.7765363128491619.
[I 2025-07-14 10:33:02,581] Trial 14 finished with value: 0.7541899441340781 and parameters: {'n_estimators': 100, 'max_depth': 9}. Best is trial 8 with value: 0.7765363128491619.
[I 2025-07-14 10:33:02,908] Trial 15 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 78, 'max_depth': 20}. Best is trial 8 with value: 0.7765363128491619.
[I 2025-07-14 10:33:03,534] Trial 16 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 165, 'max_depth': 10}. Best is trial 8 with value: 0.7765363128491619.
[I 2025-07-14 10:33:04,103] Trial 17 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 17}. Best is trial 8 with value: 0.7765363128491619.
[I 2025-07-14 10:33:04,596] Trial 18 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 137, 'max_depth': 5}. Best is trial 8 with value: 0.7765363128491619.
[I 2025-07-14 10:33:05,493] Trial 19 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 179, 'max_depth': 8}. Best is trial 8 with value: 0.7765363128491619.
[I 2025-07-14 10:33:05,777] Trial 20 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 50, 'max_depth': 14}. Best is trial 20 with value: 0.7765363128491621.
[I 2025-07-14 10:33:06,711] Trial 21 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 188, 'max_depth': 14}. Best is trial 20 with value: 0.7765363128491621.
[I 2025-07-14 10:33:07,207] Trial 22 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 124, 'max_depth': 16}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-07-14 10:33:07,583] Trial 23 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 104, 'max_depth': 6}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-07-14 10:33:08,332] Trial 24 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 196, 'max_depth': 18}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-07-14 10:33:08,697] Trial 25 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 96, 'max_depth': 13}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-07-14 10:33:09,340] Trial 26 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 167, 'max_depth': 18}. Best is trial 22 with value: 0.7783985102420856.
[I 2025-07-14 10:33:09,553] Trial 27 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 57, 'max_depth': 7}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:10,163] Trial 28 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 158, 'max_depth': 20}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:10,400] Trial 29 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 61, 'max_depth': 18}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:10,946] Trial 30 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 145, 'max_depth': 9}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:11,248] Trial 31 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 83, 'max_depth': 3}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:11,660] Trial 32 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 108, 'max_depth': 11}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:12,192] Trial 33 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 20}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:12,591] Trial 34 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 108, 'max_depth': 7}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:13,209] Trial 35 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 163, 'max_depth': 15}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:13,723] Trial 36 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 133, 'max_depth': 10}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:14,360] Trial 37 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 173, 'max_depth': 7}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:14,698] Trial 38 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 90, 'max_depth': 9}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:15,188] Trial 39 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 131, 'max_depth': 19}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:15,567] Trial 40 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 111, 'max_depth': 3}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:15,767] Trial 41 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 50, 'max_depth': 12}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:16,266] Trial 42 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 132, 'max_depth': 12}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:17,283] Trial 43 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 189, 'max_depth': 13}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:18,057] Trial 44 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 160, 'max_depth': 9}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:18,416] Trial 45 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 100, 'max_depth': 3}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:18,956] Trial 46 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 143, 'max_depth': 13}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:19,216] Trial 47 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 67, 'max_depth': 18}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:19,689] Trial 48 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 123, 'max_depth': 11}. Best is trial 27 with value: 0.7802607076350093.
[I 2025-07-14 10:33:20,144] Trial 49 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 138, 'max_depth': 3}. Best is trial 27 with value: 0.7802607076350093.

In [19]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 57, 'max_depth': 7}

In [20]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [21]:
search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [22]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2025-07-14 10:34:36,393] A new study created in memory with name: no-name-264b61c3-9347-4b35-8b3b-cdd5dc9ec408
[I 2025-07-14 10:34:36,757] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-07-14 10:34:37,333] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-07-14 10:34:37,535] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-14 10:34:37,930] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-14 10:34:38,316] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-14 10:34:38,511] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-14 10:34:39,050] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-14 10:34:39,625] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-14 10:34:40,228] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-14 10:34:40,998] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-14 10:34:41,745] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-14 10:34:42,526] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-14 10:34:43,244] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-07-14 10:34:43,437] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-07-14 10:34:43,828] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-07-14 10:34:44,046] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [23]:
# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [24]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

## Optuna Visualizations

In [33]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [34]:
# 1. Optimization History
plot_optimization_history(study).show()

In [35]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [36]:
# 3. Slice Plot
plot_slice(study).show()

In [37]:
# 4. Contour Plot
plot_contour(study).show()

In [38]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

## Optimizing Multiple ML Models

In [39]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [40]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [41]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-07-14 10:58:43,743] A new study created in memory with name: no-name-7997a4d6-4651-48bd-bf6b-53d7684ae54e
[I 2025-07-14 10:58:43,972] Trial 0 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 66, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-07-14 10:58:44,389] Trial 1 finished with value: 0.7746741154562384 and parameters: {'classifier': 'RandomForest', 'n_estimators': 139, 'max_depth': 18, 'min_samples_split': 8, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 1 with value: 0.7746741154562384.
[I 2025-07-14 10:58:45,246] Trial 2 finished with value: 0.739292364990689 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 58, 'learning_rate': 0.020220688439419297, 'max_depth': 15, 'min_samples_split': 6, 'min_samples_leaf': 2}. Best is trial 1 with value: 0.7746741154562384.
[I 2025-07-14 10:58:45,267] Trial 3 finished with value: 0.6945996275605214 and parameters: {'classifier': 'SVM', 'C': 14.686502599753855, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 1 with value: 0.7746741154562384.
[I 2025-07-14 10:58:46,897] Trial 4 finished with value: 0.756052141527002 and parameters: {'classifier': 'RandomForest', 'n_estimators': 264, 'max_depth': 19, 'min_samples_split': 10, 'min_samples_leaf': 6, 'bootstrap': True}. Best is trial 1 with value: 0.7746741154562384.
[I 2025-07-14 10:58:49,469] Trial 5 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 210, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 1, 'bootstrap': True}. Best is trial 1 with value: 0.7746741154562384.
[I 2025-07-14 10:58:49,521] Trial 6 finished with value: 0.702048417132216 and parameters: {'classifier': 'SVM', 'C': 49.886362270982744, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 1 with value: 0.7746741154562384.
[I 2025-07-14 10:58:49,587] Trial 7 finished with value: 0.7374301675977654 and parameters: {'classifier': 'SVM', 'C': 0.44295022619772784, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 1 with value: 0.7746741154562384.
[I 2025-07-14 10:58:49,714] Trial 8 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.7174642225588017, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 8 with value: 0.7858472998137801.
[I 2025-07-14 10:58:49,782] Trial 9 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 4.5873925205830375, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 8 with value: 0.7858472998137801.
[I 2025-07-14 10:58:52,011] Trial 10 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 298, 'learning_rate': 0.23273817882984402, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 9}. Best is trial 8 with value: 0.7858472998137801.
[I 2025-07-14 10:58:52,453] Trial 11 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 141, 'max_depth': 11, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 8 with value: 0.7858472998137801.
[I 2025-07-14 10:58:52,881] Trial 12 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 142, 'max_depth': 9, 'min_samples_split': 10, 'min_samples_leaf': 10, 'bootstrap': False}. Best is trial 8 with value: 0.7858472998137801.
[I 2025-07-14 10:58:52,904] Trial 13 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.25776219706829806, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 13 with value: 0.7858472998137803.
[I 2025-07-14 10:58:52,927] Trial 14 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10490855954526024, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 14 with value: 0.7877094972067038.
[I 2025-07-14 10:58:52,951] Trial 15 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12131663935392521, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:52,972] Trial 16 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10005792039314246, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:52,998] Trial 17 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 0.7148783263963966, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:53,820] Trial 18 finished with value: 0.7579143389199255 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 212, 'learning_rate': 0.0101249020385141, 'max_depth': 3, 'min_samples_split': 2, 'min_samples_leaf': 5}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:53,843] Trial 19 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12187374235004468, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:53,867] Trial 20 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.7237727109292379, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:53,889] Trial 21 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.11044035187807458, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:53,911] Trial 22 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.22102823568230495, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:53,935] Trial 23 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.1099483100126108, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:53,962] Trial 24 finished with value: 0.7690875232774674 and parameters: {'classifier': 'SVM', 'C': 1.4373425427394564, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:54,804] Trial 25 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 111, 'learning_rate': 0.14063606775825155, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 5}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:54,826] Trial 26 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.23022383770573263, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:54,850] Trial 27 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2997371192241433, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:54,875] Trial 28 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.9652061784272529, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:56,892] Trial 29 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 218, 'learning_rate': 0.05868757271141519, 'max_depth': 15, 'min_samples_split': 4, 'min_samples_leaf': 7}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:56,919] Trial 30 finished with value: 0.7541899441340782 and parameters: {'classifier': 'SVM', 'C': 0.15727435595338424, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:56,940] Trial 31 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.11501501970269441, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:56,964] Trial 32 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.35118896974313796, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:56,987] Trial 33 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15577678067179546, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:57,011] Trial 34 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.18393272465676494, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:57,034] Trial 35 finished with value: 0.7430167597765364 and parameters: {'classifier': 'SVM', 'C': 0.5027319732543676, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:57,962] Trial 36 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 256, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:57,988] Trial 37 finished with value: 0.7243947858472998 and parameters: {'classifier': 'SVM', 'C': 1.8875427076317284, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:58,681] Trial 38 finished with value: 0.756052141527002 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 95, 'learning_rate': 0.050689054107561096, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 4}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:59,339] Trial 39 finished with value: 0.7579143389199254 and parameters: {'classifier': 'RandomForest', 'n_estimators': 184, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 7, 'bootstrap': True}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:59,361] Trial 40 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10406051770159842, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:59,383] Trial 41 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10394360483271281, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:59,408] Trial 42 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17114905038571027, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:59,432] Trial 43 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.10326087825336476, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:59,457] Trial 44 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17345907646032752, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:59,499] Trial 45 finished with value: 0.6890130353817505 and parameters: {'classifier': 'SVM', 'C': 15.950102980415492, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:58:59,536] Trial 46 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.3637845312156236, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:00,920] Trial 47 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 285, 'max_depth': 12, 'min_samples_split': 3, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:00,946] Trial 48 finished with value: 0.7039106145251397 and parameters: {'classifier': 'SVM', 'C': 74.53822402950145, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:01,021] Trial 49 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 19.431058746017, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:02,209] Trial 50 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 179, 'learning_rate': 0.06576526430511208, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 8}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:02,233] Trial 51 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13745661433155298, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:02,255] Trial 52 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14664085396982432, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:02,285] Trial 53 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 6.6670549715550385, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:02,310] Trial 54 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.15854748343369895, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:02,333] Trial 55 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2811919085236226, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:02,356] Trial 56 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.46151236347906566, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:02,382] Trial 57 finished with value: 0.7206703910614524 and parameters: {'classifier': 'SVM', 'C': 0.2550443762896904, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:03,235] Trial 58 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 233, 'max_depth': 13, 'min_samples_split': 9, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:03,263] Trial 59 finished with value: 0.750465549348231 and parameters: {'classifier': 'SVM', 'C': 0.13248766718644514, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:03,290] Trial 60 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2042479042459622, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:03,313] Trial 61 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1348484536385852, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:03,335] Trial 62 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13772488663634722, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:03,357] Trial 63 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1422586071021492, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:03,383] Trial 64 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.2210943007699989, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:03,408] Trial 65 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14308477969976055, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:03,446] Trial 66 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.35945877159305223, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:03,472] Trial 67 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.6026894451555956, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:04,336] Trial 68 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 89, 'learning_rate': 0.022761741361698475, 'max_depth': 17, 'min_samples_split': 5, 'min_samples_leaf': 6}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:04,361] Trial 69 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.1299981980207586, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:04,383] Trial 70 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.21670011126314218, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:04,407] Trial 71 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.132550139835193, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:04,428] Trial 72 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.13755389272006188, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:04,455] Trial 73 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.19157263754903656, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:04,489] Trial 74 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.28034186705586095, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:04,514] Trial 75 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.12644392680815916, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:04,537] Trial 76 finished with value: 0.7877094972067038 and parameters: {'classifier': 'SVM', 'C': 0.17781505410792442, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:05,014] Trial 77 finished with value: 0.7802607076350093 and parameters: {'classifier': 'RandomForest', 'n_estimators': 159, 'max_depth': 5, 'min_samples_split': 7, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:05,044] Trial 78 finished with value: 0.7653631284916201 and parameters: {'classifier': 'SVM', 'C': 0.10408288814849762, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:05,927] Trial 79 finished with value: 0.7374301675977654 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 119, 'learning_rate': 0.2670885054588037, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 9}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:05,948] Trial 80 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.31255189446908344, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.
[I 2025-07-14 10:59:05,972] Trial 81 finished with value: 0.7895716945996275 and parameters: {'classifier': 'SVM', 'C': 0.14816486908578147, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 15 with value: 0.7895716945996275.

In [42]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.12131663935392521, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [43]:
study.trials_dataframe()

,number,value,datetime_start,datetime_complete,duration,params_C,params_bootstrap,params_classifier,params_gamma,params_kernel,params_learning_rate,params_max_depth,params_min_samples_leaf,params_min_samples_split,params_n_estimators,state
0,0,0.769088,2025-07-14 10:58:43.744388,2025-07-14 10:58:43.972334,0 days 00:00:00.227946,NaN,False,RandomForest,NaN,NaN,NaN,10.0,3.0,4.0,66.0,COMPLETE
1,1,0.774674,2025-07-14 10:58:43.973059,2025-07-14 10:58:44.389540,0 days 00:00:00.416481,NaN,False,RandomForest,NaN,NaN,NaN,18.0,8.0,8.0,139.0,COMPLETE
2,2,0.739292,2025-07-14 10:58:44.390339,2025-07-14 10:58:45.246732,0 days 00:00:00.856393,NaN,NaN,GradientBoosting,NaN,NaN,0.020221,15.0,2.0,6.0,58.0,COMPLETE
3,3,0.694600,2025-07-14 10:58:45.247484,2025-07-14 10:58:45.267879,0 days 00:00:00.020395,14.686503,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
4,4,0.756052,2025-07-14 10:58:45.268676,2025-07-14 10:58:46.897919,0 days 00:00:01.629243,NaN,True,RandomForest,NaN,NaN,NaN,19.0,6.0,10.0,264.0,COMPLETE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,0.743017,2025-07-14 10:59:07.271643,2025-07-14 10:59:07.299509,0 days 00:00:00.027866,0.117931,NaN,SVM,auto,rbf,NaN,NaN,NaN,NaN,NaN,COMPLETE
96,96,0.785847,2025-07-14 10:59:07.300428,2025-07-14 10:59:07.339029,0 days 00:00:00.038601,6.055523,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE
97,97,0.772812,2025-07-14 10:59:07.339641,2025-07-14 10:59:07.374655,0 days 00:00:00.035014,0.152089,NaN,SVM,scale,sigmoid,NaN,NaN,NaN,NaN,NaN,COMPLETE
98,98,0.744879,2025-07-14 10:59:07.375276,2025-07-14 10:59:08.806915,0 days 00:00:01.431639,NaN,NaN,GradientBoosting,NaN,NaN,0.113596,8.0,7.0,5.0,188.0,COMPLETE
99,99,0.785847,2025-07-14 10:59:08.807582,2025-07-14 10:59:08.840746,0 days 00:00:00.033164,1.875392,NaN,SVM,auto,linear,NaN,NaN,NaN,NaN,NaN,COMPLETE

In [44]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 78
RandomForest        12
GradientBoosting    10
Name: count, dtype: int64

In [45]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.745996
RandomForest        0.768312
SVM                 0.774746
Name: value, dtype: float64

In [46]:
# 1. Optimization History
plot_optimization_history(study).show()

In [47]:
# 3. Slice Plot
plot_slice(study).show()

In [48]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [53]:
#YET TO LEARN ABOUT THE XGBOOST AND THEN OPTUNA
      # FOR IT'S DETAILED HYPERPARAMETER TUNING

# import optuna
# import xgboost as xgb
# from sklearn.model_selection import train_test_split
# from sklearn.datasets import load_iris
# from sklearn.metrics import accuracy_score
# import numpy as np

# # Load the Iris dataset
# X, y = load_iris(return_X_y=True)

# # Split the dataset into training and test sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Define the objective function for XGBoost
# def objective(trial):
#     # Hyperparameter search space
#     param = {
#         'verbosity': 0,
#         'objective': 'multi:softprob',
#         'num_class': 3,
#         'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
#         'booster': 'gbtree',
#         'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
#         'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
#         'eta': trial.suggest_float('eta', 0.01, 0.3),
#         'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
#         'max_depth': trial.suggest_int('max_depth', 3, 9),
#         'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
#         'subsample': trial.suggest_float('subsample', 0.4, 1.0),
#         'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
#         'n_estimators': 300,
#     }

#     # Create DMatrix for XGBoost
#     dtrain = xgb.DMatrix(X_train, label=y_train)
#     dtest = xgb.DMatrix(X_test, label=y_test)

#     # Define a pruning callback based on evaluation metrics
#     pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

#     # Train the model
#     bst = xgb.train(
#         param,
#         dtrain,
#         num_boost_round=300,
#         evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
#         early_stopping_rounds=30,
#         callbacks=[pruning_callback]
#     )

#     # Predict on the test set
#     preds = bst.predict(dtest)
#     best_preds = [int(np.argmax(line)) for line in preds]

#     # Return accuracy as the objective value
#     accuracy = accuracy_score(y_test, best_preds)
#     return accuracy

# # Create a study with pruning
# study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
# study.optimize(objective, n_trials=50)

# # Output the best trial
# print(f"Best trial: {study.best_trial.params}")
# print(f"Best accuracy: {study.best_value}")

In [54]:
# ! pip install optuna-integration[xgboost]

In [55]:
# from optuna.visualization import plot_intermediate_values

# # 1. Plot intermediate values during the trials
# plot_intermediate_values(study).show()